package com.guge.seckill.dataobject;

public class UserPasswordDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_password.id
     *
     * @mbggenerated Tue Jan 11 00:54:16 CST 2022
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_password.encript_password
     *
     * @mbggenerated Tue Jan 11 00:54:16 CST 2022
     */
    private String encriptPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_password.user_id
     *
     * @mbggenerated Tue Jan 11 00:54:16 CST 2022
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_password.id
     *
     * @return the value of user_password.id
     *
     * @mbggenerated Tue Jan 11 00:54:16 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_password.id
     *
     * @param id the value for user_password.id
     *
     * @mbggenerated Tue Jan 11 00:54:16 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_password.encript_password
     *
     * @return the value of user_password.encript_password
     *
     * @mbggenerated Tue Jan 11 00:54:16 CST 2022
     */
    public String getEncriptPassword() {
        return encriptPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_password.encript_password
     *
     * @param encriptPassword the value for user_password.encript_password
     *
     * @mbggenerated Tue Jan 11 00:54:16 CST 2022
     */
    public void setEncriptPassword(String encriptPassword) {
        this.encriptPassword = encriptPassword == null ? null : encriptPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_password.user_id
     *
     * @return the value of user_password.user_id
     *
     * @mbggenerated Tue Jan 11 00:54:16 CST 2022
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_password.user_id
     *
     * @param userId the value for user_password.user_id
     *
     * @mbggenerated Tue Jan 11 00:54:16 CST 2022
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}